dist: trusty
language: scala
scala:
  - 2.11.12
  - 2.12.4
jdk:
  - oraclejdk7
  - openjdk7
  - oraclejdk8
  - openjdk8
test:
  - sbt ++$TRAVIS_SCALA_VERSION test
  - sbt ++$TRAVIS_SCALA_VERSION scalastyle
